services:
  # Django Web Service
  - type: web
    name: django-travel-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libxml2-dev libxslt1-dev python3-dev gcc build-essential
      pip install --upgrade pip setuptools wheel
      export CFLAGS="-O0"
      export CPPFLAGS="-O0"
      pip install --no-cache-dir -r requirements.txt
      python -c "import django; print('Django version:', django.get_version())"
      python -c "import sys; print('Python path:', sys.path)"
      python manage.py check --deploy
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py setup_media
    startCommand: "cd /opt/render/project/src && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: travel-partner-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"

databases:
  # PostgreSQL Database
  - name: travel-partner-db
    plan: free
    databaseName: travel_partner_db
    user: travel_partner_user 